### ISSUE TITLE
Make customization easier

### ISSUE THREAD

**Issue by TheHadiAhmadi** [ubeac/svelte-components#166]
one solution is to use ubeac prefixed classes for all components, then we can customize style of component using css.

for example: 
```css
.ubeac-checkbox {
  margin: 2px;
}
.ubeac-checkbox-label {
  font-size: 14px;
}

```
